//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public System.Guid AchievementGuid { get; set; }
        public long AchievementIntId { get; set; }
        public string Title { get; set; }
        public string EmployeeName { get; set; }
        public string Comment { get; set; }
        public byte[] Imagedata { get; set; }
    }
}
