//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public System.Guid CommitteeMemberGuid { get; set; }
        public long CommiteeIntId { get; set; }
        public long MemberIntId { get; set; }
        public long CommitteeMemberIntId { get; set; }
    
        public virtual Committee Committee { get; set; }
        public virtual User User { get; set; }
    }
}
