//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeEvent
    {
        public System.Guid EventGuid { get; set; }
        public long EventIntId { get; set; }
        public string EventName { get; set; }
        public Nullable<long> CommiteeIntId { get; set; }
        public string EventDescription { get; set; }
    
        public virtual Committee Committee { get; set; }
    }
}
