//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITPolicy
    {
        public System.Guid ITPoliciesGuid { get; set; }
        public long ITPoliciesIntId { get; set; }
        public string ITPoliciesName { get; set; }
        public string ITPoliciesDetails { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string PoliciesFullDetails { get; set; }
    }
}
