//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliciesProcedure
    {
        public System.Guid PoliciesProcedureGuid { get; set; }
        public long PoliciesProcedureIntId { get; set; }
        public string PoliciesProcedureName { get; set; }
        public string PoliciesProcedureDetails { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string PoliciesFullDetails { get; set; }
    }
}
