//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public System.Guid TeamGuid { get; set; }
        public long TeamIntId { get; set; }
        public string TeamName { get; set; }
    }
}
