//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GicPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CommitteeMembers = new HashSet<CommitteeMember>();
            this.User1 = new HashSet<User>();
        }
    
        public long UserIntId { get; set; }
        public System.Guid UserGuid { get; set; }
        public long EmployeeId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> SupervisorIntId { get; set; }
        public string Designation { get; set; }
        public string Summary { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string DeskNo { get; set; }
        public Nullable<long> Extension { get; set; }
        public long Team { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string About { get; set; }
        public byte[] Imagedata { get; set; }
        public string ContactNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeMember> CommitteeMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
